### ISSUE TITLE
VSCode のための最適化

### ISSUE THREAD

**Issue by watagit** [bislab-temporary/docker-template#14]
## ✨ Summary

VSCode で使いやすいようにカスタマイズする

**Comment by watagit** [comment]
@mikiya1130
森崎くんのこのイシューお願いしてもいい？森崎くんの好きなように VSCode 周りの設定ファイルをいじってもらって、みんながそれに合わせる感じで行きたいなと思っている
私普段 VSCode 使わないから、VSCode 使ってる人がやった方が良いと思って 🙄 

具体的に設定してほしいのは、`.devcontainer`と`.vscode`の部分かな〜と
それ以外にも VSCode に最適化できそうなところがあったらやってもらいたい！

**Comment by mikiya1130** [comment]
@watagit 了解です！
